steps:
  # Clone repository
  - name: 'gcr.io/cloud-builders/docker'
    id: Clone repo
    entrypoint: git
    args: ['clone', 'https://github.com/nuwe-io/mms-cloud-skeleton']
    dir: 'repo'
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/mms-front', 
           '.']
    dir: 'repo/mms-cloud-skeleton'      
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/mms-front']